# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('address', models.CharField(max_length=254, verbose_name='Hostname/IP')),
            ],
            options={
                'verbose_name_plural': 'Servers',
                'verbose_name': 'Server',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project')),
            ],
            options={
                'verbose_name_plural': 'Stages',
                'verbose_name': 'Stage',
            },
        ),
        migrations.AddField(
            model_name='server',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Stage', verbose_name='Stage'),
        ),
    ]
