# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160510_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project'),
            preserve_default=False,
        ),
    ]
