# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20160510_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='DNS name or IP address', max_length=254, verbose_name='Hostname/IP')),
                ('alias', models.CharField(blank=True, help_text='Human readable value (optional)', max_length=255, null=True, verbose_name='Human readable name')),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='stage',
            name='hosts',
            field=models.ManyToManyField(to='projects.Host'),
        ),
    ]
