# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
        ('projects', '0006_auto_20160515_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('is_active', models.BooleanField(verbose_name='Is active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='stage',
            name='hosts',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.AddField(
            model_name='hostconfig',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.Host', verbose_name='Host'),
        ),
        migrations.AddField(
            model_name='hostconfig',
            name='ssh_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.SSHConfig', verbose_name='SSH Config'),
        ),
        migrations.AddField(
            model_name='hostconfig',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Stage', verbose_name='Stage'),
        ),
    ]
