# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='DNS name or IP address', max_length=254, verbose_name='Hostname/IP')),
                ('alias', models.CharField(blank=True, help_text='Human readable value (optional)', max_length=255, null=True, verbose_name='Human readable name')),
            ],
            options={
                'verbose_name_plural': 'Hosts',
                'verbose_name': 'Host',
            },
        ),
        migrations.CreateModel(
            name='SSHConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('remote_user', models.CharField(max_length=100, verbose_name='Remove User')),
                ('private_key', models.TextField(verbose_name='Private Key')),
            ],
            options={
                'verbose_name_plural': 'SSHConfig',
                'verbose_name': 'SSHConfig',
            },
        ),
    ]
