# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_server_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Idle'), (2, 'Processing'), (3, 'Completed')], verbose_name='Status')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Stage')),
            ],
        ),
    ]
