# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 21:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deploys', '0002_auto_20160510_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('times_used', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='deploy',
            name='comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deploy',
            name='configuration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deploy',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deploy',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deploy',
            name='status',
            field=models.IntegerField(choices=[(1, 'Idle'), (2, 'Processing'), (3, 'Completed')], default=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='deploy',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deploys.Task'),
        ),
    ]
