# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploys', '0003_auto_20160513_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='log_file',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deploys.Task'),
        ),
    ]
